language: python
dist: trusty
python:
  - '2.7'
install:
  - pip install -r requirements/pip.txt
  - pip install -e .
script:
  - export PKG_VERSION=$(git describe --abbrev=0 --tags)
  - env | grep PKG_VERSION
# before_deploy:
  # - sed -i 's/0\.0\.0/'"$VERSION"'/g' setup.py
  # - cat setup.py
deploy:
  provider: pypi
  on:
    tags: true
  distributions: bdist_wheel
  skip_existing: true
  user: __token__
  password:
    secure: Xt3DkLWOcq5DSpG/pialABnQspouZWlacp3h+cdt24bA7ig8neOelYnzVynIcPOk/1W9wEohRR90/Lz1dqSvLcBTwR/bsRLRvuq+53EDInbkuDRU52kh+XiafQygIftJdDbIIT0sdZFWCoJPES1G2afPQeVHt1seFkVFr8WuZFgcCSS7LHJkTax2pEL5jKzxmxvI6L5zzsLfAOQhRiOPcYPnpg9W+QuPfuJrcgZEidfDBehmbZ541OjoUTWJyWIrkZdA3ONmueacZsb8lWtegHiZWzYiVW5HzrWF8H/uQNO2v6/Z+AMiYrTrX4tAL9vc3l8iUlVzRedfXADLWzW3Cvq2aAjj+qaXIu+J4dN99JQYHezTR7CesNT+/zliHxTjU2b9P4HGbQgy2JfJA8zljDfDNqlVZcvmDPTpYNJqKr+7NnnZ8QtC+K7PpnTXYTFqrHwzut1anGx6dcIYIP9g1MOn7vgNQf5S4A4BbVkeWPkkrGED+c6+/RKWWm7s66ROEW12svAG2XIkYzfS+IyLd4oCfprldsbGOPMHkcnpfQsT7GXBWO4rkTIdC9HR2Jp14yxwPSZRwohXQ5CsrzprmpTHXlgeksS9UN79EUunbMRxZWKnje9PDp1IJr8lJd3x4i6jaycYtFLMBO4ckRHtahrk9tcvtqrO1JtSaWa29UI=
