language: python
dist: trusty
python:
  - '2.7'
install:
  - pip install -r requirements/pip.txt
  - pip install -e .
  - python -c 'import pkg_resources; print("export VERSION={}".format(pkg_resources.get_distribution("mohand").version))'
    > VERSION && source VERSION
script:
  - echo "No Test"
deploy:
  provider: pypi
  on:
    tags: true
  distributions: bdist_wheel
  skip_existing: true
  user: moore
  password:
    secure: izdkWccMEG893UMaEn/oExtkGdXKUnfwS7bvcfcMhQfH56e6n9CotQRY6QMWTdt5bS4z9H3DypxVykDRCLn+JmoiUxoPmLFzu+4FPp7QMYq1EcF33fNQDqLtFJlWtznJYbJtp8xAYUWbQ7CIunKAOD8FHy+PiVnO5k5+ydVLCo7Wol98CNae8uVHps4v8ircQYAiee49pE3nJJvswfVr+eGIjzAknkK0aCGWNB86kc/s0RZJQNXvmgSFTvS6AljR5m7S3/W3mJSboJGG2OG/JHv4spm85D5sfeVDC+FYWKurJoN7DSqiz3KsFcbrvOlGG2dMrqWhPb2NqgfZCUEof2dulbMbVHKqLZLApfbb2Mr13p5gC/KlxDSZCako6OXSyzGfOdVgUfSSQdZsh2csOv/gfBUmVxQACIUWT3FELO/sfLBNC3xKoU4zYqcRDJfPDEMitujkws36afFA2JijRZ5xFvorEkEyjg9rSrKL/9XwWb3psx+PCfoSOyTmYa2w9fOsGSaYFQNKoqrq0rKhqZABZJStmkC8gkD65xlc1UXrIaLVjY561NP3LBR5QRp5UjnLf2jKOpsw0W8Au3mbpwIOkWqdGpSngPA/2ZjqIXaMEwaHLC0lYLnaL700fp8uXELONfcIU/g1WixktV7PBh+vi4EhEEA3aho2K8qNLfo=
